name: CommonWorkflow

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
      - reopened
  workflow_dispatch:
  workflow_call:
  
  
jobs:
  workflow-CI:
    name: 'Workflow'
    runs-on: ubuntu-latest

    steps:
    - name: Download xxx.sh script
      run: |          
          TOKEN=${{ secrets.TESTPAT }} 
          echo ${{ secrets.TESTPAT }} 
          REPO="e-eman/CommonWorkflow"
          BRANCH="main"
          FILE_PATH=".github/scripts/test.sh"

          # Make API request to get the file content
          RESPONSE=$(curl -L -H "Accept: application/vnd.github.raw" -H "Authorization: Bearer $TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/$REPO/contents/$FILE_PATH?ref=$BRANCH)
          
          # Save the response content to a file
          echo "$RESPONSE" > test.sh
          
          # Set execute permission
          chmod +x test.sh
          #cat test.sh
          echo "Start the script"
          COMMENT="Hello"
          ./test.sh $TOKEN $COMMENT ${{ github.repository }} ${{ github.event.pull_request.number }}
          #./test.sh $COMMENT ${{ github.event.pull_request.number }} $TOKEN ${{ github.repository }}
          
          
          
          
